  const products = [
  // 🟤 GRAINS & CEREALS
  {
    name: "Aashirvaad Atta 10kg",
    description: "High-quality whole wheat flour for soft and fluffy rotis.",
    price: 520,
    offerPrice: 485,
    images: ["/wheat1.png", "/wheat2.png", "/wheat3.png", "/wheat4.png"],
    category: "grains & cereals",
    stockQuantity: 100,
    inStock: true,
  },
  {
    name: "Fortune Basmati Rice 5kg",
    description: "Long-grain aromatic basmati rice ideal for biryani and pulao.",
    price: 640,
    offerPrice: 599,
    images: ["/rice1.png"],
    category: "grains & cereals",
    stockQuantity: 80,
    inStock: true,
  },
  {
    name: "Tata Salt 1kg",
    description: "Vacuum-evaporated iodized salt for a healthy lifestyle.",
    price: 28,
    offerPrice: 25,
    images: ["/tataSalt.png"],
    category: "grains & cereals",
    stockQuantity: 200,
    inStock: true,
  },
  {
    name: "Rolled Oats 1kg",
    description: "Whole-grain rolled oats rich in fiber and protein.",
    price: 180,
    offerPrice: 160,
    images: ["/oats.png"],
    category: "grains & cereals",
    stockQuantity: 90,
    inStock: true,
  },
  {
    name: "Poha 1kg",
    description: "Flattened rice flakes perfect for quick breakfasts.",
    price: 65,
    offerPrice: 55,
    images: ["/poha1.webp"],
    category: "grains & cereals",
    stockQuantity: 150,
    inStock: true,
  },

  // 🥛 DAIRY PRODUCTS
  {
    name: "Cheese 500g",
    description: "Rich and creamy cheese made from pure cow’s milk.",
    price: 290,
    offerPrice: 270,
    images: ["/cheese.png"],
    category: "dairy products",
    stockQuantity: 120,
    inStock: true,
  },
  {
    name: "Amul Milk 1L",
    description: "Pasteurized full cream milk for daily nutrition.",
    price: 65,
    offerPrice: 60,
    images: ["/amulMilk.png"],
    category: "dairy products",
    stockQuantity: 200,
    inStock: true,
  },
  {
    name: "Dahi 250g",
    description: "Thick and creamy curd made from fresh milk.",
    price: 50,
    offerPrice: 45,
    images: ["/dahi1.png"],
    category: "dairy products",
    stockQuantity: 60,
    inStock: true,
  },
  {
    name: "Paneer 200g",
    description: "Fresh, soft paneer made from cow’s milk.",
    price: 90,
    offerPrice: 80,
    images: ["/paneer1.png", "/paneer2.png"],
    category: "dairy products",
    stockQuantity: 85,
    inStock: true,
  },

  // 🍜 INSTANT FOODS
  {
    name: "Maggie 8 Pack (560g)",
    description: "Instant noodles with the signature masala flavor.",
    price: 120,
    offerPrice: 110,
    images: ["/maggi.png"],
    category: "instant foods",
    stockQuantity: 180,
    inStock: true,
  },
  {
    name: "Yippee Noodles 70g",
    description: "Ready-to-eat noodles packed with spicy vegetable flavors.",
    price: 50,
    offerPrice: 45,
    images: ["/yippee.png"],
    category: "instant foods",
    stockQuantity: 90,
    inStock: true,
  },
  {
    name: "Glucon-D Nimbu Pani 1kg",
    description: "Instant energy drink with lemon water flavor.",
    price: 180,
    offerPrice: 165,
    images: ["/glucose.png"],
    category: "instant foods",
    stockQuantity: 100,
    inStock: true,
  },
  {
    name: "Kissan Mixed Fruit Jam 500g",
    description: "Delicious fruit jam made with 100% real fruits.",
    price: 190,
    offerPrice: 170,
    images: ["/jam1.png", "/jam2.png"],
    category: "instant foods",
    stockQuantity: 80,
    inStock: true,
  },
  {
    name: "Schezwan Chutney 250g",
    description: "Spicy and tangy chutney perfect for snacks.",
    price: 95,
    offerPrice: 85,
    images: ["/chutney.png"],
    category: "instant foods",
    stockQuantity: 130,
    inStock: true,
  },

  // 🌶️ SPICES
  {
    name: "MDH Garam Masala 100g",
    description: "Blend of aromatic spices for Indian cooking.",
    price: 85,
    offerPrice: 75,
    images: ["/mdh.png"],
    category: "spices",
    stockQuantity: 90,
    inStock: true,
  },
  {
    name: "Red Chilli Powder 100g",
    description: "Fine, vibrant red chilli powder for spicy flavor.",
    price: 80,
    offerPrice: 70,
    images: ["/chillipowder.png"],
    category: "spices",
    stockQuantity: 110,
    inStock: true,
  },

  // 🥦 VEGETABLES
  {
    name: "Tomato (1kg)",
    description: "Fresh, ripe tomatoes perfect for curries and salads.",
    price: 45,
    offerPrice: 40,
    images: ["/tamatar_1.png", "/tamatar_2.png"],
    category: "vegetables",
    stockQuantity: 150,
    inStock: true,
  },
  {
    name: "Onion (1kg)",
    description: "Firm, fresh onions ideal for everyday cooking.",
    price: 50,
    offerPrice: 45,
    images: ["/onion_image_1.png"],
    category: "vegetables",
    stockQuantity: 170,
    inStock: true,
  },
  {
    name: "Potato (1kg)",
    description: "Premium quality potatoes rich in starch.",
    price: 40,
    offerPrice: 35,
    images: ["/potato1.png", "/potato2.png", "/potato3.png", "/potato4.png"],
    category: "vegetables",
    stockQuantity: 160,
    inStock: true,
  },
  {
    name: "Spinach (250g)",
    description: "Fresh spinach leaves rich in iron and nutrients.",
    price: 25,
    offerPrice: 20,
    images: ["/spinach_image_1.png"],
    category: "vegetables",
    stockQuantity: 100,
    inStock: true,
  },

  // 🍎 FRUITS
  {
    name: "Banana (1 Dozen)",
    description: "Fresh and ripe bananas full of natural sweetness.",
    price: 60,
    offerPrice: 55,
    images: ["/banana_image_1.png"],
    category: "fruits",
    stockQuantity: 90,
    inStock: true,
  },
  {
    name: "Apple (1kg)",
    description: "Crisp, juicy apples rich in fiber and vitamins.",
    price: 180,
    offerPrice: 160,
    images: ["/apple_image.png"],
    category: "fruits",
    stockQuantity: 70,
    inStock: true,
  },
  {
    name: "Orange (1kg)",
    description: "Sweet and tangy oranges packed with Vitamin C.",
    price: 120,
    offerPrice: 110,
    images: ["/orange_image.png"],
    category: "fruits",
    stockQuantity: 75,
    inStock: true,
  },
  {
    name: "Carrot (500g)",
    description: "Rich source of vitamin A, good for eyes",
    price: 90,
    offerPrice: 80,
    images: ["/carrot_image.png"],
    category: "fruits",
    stockQuantity: 85,
    inStock: true,
  },
];

module.exports = products;
